-- データベース構築
CREATE DATABASE IF NOT EXISTS REHYOGO;

-- 使用データベース選択
USE REHYOGO;

-- TAGS_CATEGORYテーブル作成 ここから
CREATE TABLE IF NOT EXISTS TAGS_CATEGORY (
ID INT AUTO_INCREMENT PRIMARY KEY
,CATEGORY_NAME VARCHAR(10) NOT NULL
);
-- TAGS_CATEGORYテーブル作成 ここまで

-- EVENTS_STATUSテーブル作成 ここから
CREATE TABLE IF NOT EXISTS EVENTS_STATUS (
ID INT AUTO_INCREMENT PRIMARY KEY
,EVENTS_STATUS_NAME VARCHAR(10) NOT NULL
);
-- EVENTS_STATUSテーブル作成 ここまで

-- USERS_STATUSテーブル作成 ここから
CREATE TABLE IF NOT EXISTS USERS_STATUS (
ID INT AUTO_INCREMENT PRIMARY KEY
,USERS_STATUS_NAME VARCHAR(10) NOT NULL
);
-- USERS_STATUSテーブル作成 ここまで

-- USERSテーブル作成 ここから
CREATE TABLE IF NOT EXISTS USERS (
ID INT AUTO_INCREMENT PRIMARY KEY
,MST_USER_ID VARCHAR(20) NOT NULL UNIQUE
,USER_PASSWORD VARCHAR(400) NOT NULL
,IS_ADMIN BOOLEAN DEFAULT FALSE
,USERS_STATUS_ID INT DEFAULT 1 NOT NULL,
FOREIGN KEY (USERS_STATUS_ID) REFERENCES USERS_STATUS(ID)
);
-- USERSテーブル作成 ここまで

-- PINSテーブル作成 ここから
CREATE TABLE IF NOT EXISTS PINS (
ID INT AUTO_INCREMENT PRIMARY KEY
,USERS_USER_ID VARCHAR(20) NOT NULL
,FOREIGN KEY (USERS_USER_ID) REFERENCES USERS(MST_USER_ID)
,PIN_NAME VARCHAR(50) NOT NULL UNIQUE
,PIN_ADDRESS VARCHAR(50) NOT NULL
,PIN_URL VARCHAR(400)
,PIN_GEO_X DECIMAL(10,7) NOT NULL
,PIN_GEO_Y DECIMAL(10,7) NOT NULL
,PIN_IMAGE_URL VARCHAR(400)
,PIN_INFO VARCHAR(250)
,PIN_TIMESTAMP TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
-- PINSテーブル作成 ここまで

-- REVIEWSテーブル作成 ここから
CREATE TABLE IF NOT EXISTS REVIEWS (
ID INT AUTO_INCREMENT PRIMARY KEY
,USERS_USER_ID VARCHAR(20) NOT NULL
,FOREIGN KEY (USERS_USER_ID) REFERENCES USERS(MST_USER_ID)
,PINS_ID INT NOT NULL
,FOREIGN KEY (PINS_ID) REFERENCES PINS(ID)
,REVIEW_TITLE VARCHAR(20) NOT NULL
,REVIEW_CONTENTS VARCHAR(250) NOT NULL
,REVIEW_TIMESTAMP TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
-- REVIEWSテーブル作成 ここまで

-- EVENTSテーブル作成 ここから
CREATE TABLE IF NOT EXISTS EVENTS (
ID INT AUTO_INCREMENT PRIMARY KEY
,USERS_USER_ID VARCHAR(20) NOT NULL
,FOREIGN KEY (USERS_USER_ID) REFERENCES USERS(MST_USER_ID)
,EVENT_NAME VARCHAR(50) NOT NULL UNIQUE
,EVENT_ADDRESS VARCHAR(50) NOT NULL
,EVENT_URL VARCHAR(400)
,EVENT_GEO_X DECIMAL(10,7) NOT NULL
,EVENT_GEO_Y DECIMAL(10,7) NOT NULL
,EVENT_IMAGE_URL VARCHAR(400)
,EVENT_INFO VARCHAR(250)
,EVENT_START DATE NOT NULL
,EVENT_END DATE NOT NULL
,EVENT_STATUS_ID INT NOT NULL DEFAULT 1
,FOREIGN KEY (EVENT_STATUS_ID) REFERENCES EVENTS_STATUS(ID) 
,EVENT_TIMESTAMP TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
-- EVENTSテーブル作成 ここまで

-- PINS_FAVORITEテーブル作成 ここから
CREATE TABLE IF NOT EXISTS PINS_FAVORITE (
ID INT AUTO_INCREMENT UNIQUE
,USERS_USER_ID VARCHAR(20) NOT NULL
,FOREIGN KEY (USERS_USER_ID) REFERENCES USERS(MST_USER_ID)
,PINS_ID INT NOT NULL
,FOREIGN KEY (PINS_ID) REFERENCES PINS(ID)
,PINS_FAVORITE_TIMESTAMP TIMESTAMP DEFAULT CURRENT_TIMESTAMP
,PRIMARY KEY(USERS_USER_ID,PINS_ID)
);
-- PINS_FAVORITEテーブル作成 ここまで

-- REVIEWS_FAVORITEテーブル作成 ここから
CREATE TABLE IF NOT EXISTS REVIEWS_FAVORITE (
ID INT AUTO_INCREMENT UNIQUE
,USERS_USER_ID VARCHAR(20) NOT NULL
,FOREIGN KEY (USERS_USER_ID) REFERENCES USERS(MST_USER_ID)
,REVIEWS_ID INT NOT NULL
,FOREIGN KEY (REVIEWS_ID) REFERENCES REVIEWS(ID)
,REVIEWS_FAVORITE_TIMESTAMP TIMESTAMP DEFAULT CURRENT_TIMESTAMP
,PRIMARY KEY(USERS_USER_ID,REVIEWS_ID)
);
-- REVIEWS_FAVORITEテーブル作成 ここまで

-- EVENTS_FAVORITEテーブル作成 ここから
CREATE TABLE IF NOT EXISTS EVENTS_FAVORITE (
ID INT AUTO_INCREMENT UNIQUE
,USERS_USER_ID VARCHAR(20) NOT NULL
,FOREIGN KEY (USERS_USER_ID) REFERENCES USERS(MST_USER_ID)
,EVENTS_ID INT NOT NULL
,FOREIGN KEY (EVENTS_ID) REFERENCES EVENTS(ID)
,EVENT_FAVORITE_TIMESTAMP TIMESTAMP DEFAULT CURRENT_TIMESTAMP
,PRIMARY KEY(USERS_USER_ID,EVENTS_ID)
);
-- EVENTS_FAVORITEテーブル作成 ここまで

-- PIN_TAGSテーブル作成 ここから
CREATE TABLE IF NOT EXISTS PIN_TAGS (
ID INT AUTO_INCREMENT UNIQUE
,PINS_ID INT NOT NULL
,FOREIGN KEY (PINS_ID) REFERENCES PINS(ID)
,TAGS_CATEGORY_ID INT NOT NULL
,FOREIGN KEY (TAGS_CATEGORY_ID) REFERENCES TAGS_CATEGORY(ID)
,PRIMARY KEY(PINS_ID,TAGS_CATEGORY_ID)
);
-- PIN_TAGSテーブル作成 ここまで

-- !!! DROP文 !!!
-- DROP DATABASE REHYOGO;
